imagePortal/imagePortal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

imagePortal/images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^uploadImage', views.image_upload, name='uploadImage'),
    url(r'^ranking/$', views.image_ranking, name='create'),
]

imagePortal/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    url = models.URLField(blank=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                    related_name='images_liked',
                                    blank=True)

    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    #powyzsza kolumna pozwala na przechowywanie całkowitej liczby userów, którzy
    #polubili dane zdjecie


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    class Meta:
        ordering = ["-image"]

imagePortal/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('Podany adres URL nie zawiera ' \
                                        'obrazów w obsługiwanym formacie.')
        return url

    def save(self, force_insert=False,
                   force_update=False,
                   commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())

        # Pobranie pliku obrazu z podanego adresu URL.
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image', 'title', 'description')

    def save(self, force_insert=False,
                   force_update=False,
                   commit=True):

        image = super(UploadImageForm, self).save(commit=False)
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())

        # Pobranie pliku obrazu z podanego adresu URL.
        response = request.urlopen(image_title)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

imagePortal/images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .forms import UploadImageForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
import redis
from django.conf import settings

r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)


@login_required
def image_upload(request):
    if request.method == 'POST':
        upload_form = UploadImageForm(request.POST, request.FILES)
        if ulpoad_form.is_valid():
            new_item=upload_form.save(commit=False)
            new_item.image=request.FILES['image']
            new_item.save()
            messages.success(request, 'Obraz został dodany.')
            return redirect('new_item.get_absolute_url()')
    else:
        upload_form=UploadImageForm()
    return render(request, 'images/image/upload_image.html',
                  {'upload_form': upload_form, 'section': 'images' })


@login_required
def image_create(request):
    if request.method == 'POST':
        # Formularz został wysłany.
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # Dane formularza są prawidłowe.
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # Przypisanie bieżącego użytkownika do elementu.
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'Added Image', new_item)
            messages.success(request, 'Obraz został dodany.')
            # Przekierowanie do widoku szczegółowego
            # dla nowo utworzonego elementu.
            return redirect(new_item.get_absolute_url())
    else:
        # Utworzenie formularza na podstawie danych
        # i  dostarczonych przez bookmarklet w żądaniu GET.
        form = ImageCreateForm(data=request.GET)

    return render(request,
                  'images/image/create.html',
                  {'section': 'images',
                   'form': form})

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # Inkrementacja o 1 całkowitej liczby wyświetleń danego obrazu.
    total_views = r.incr('image:{}:views'.format(image.id))
    # Inkrementacja o 1 rankingu danego obrazu.
    r.zincrby('image_ranking', image.id, 1)
    return render(request, 'images/image/detail.html',
                  {'section': 'images',
                   'image': image,
                   'total_views': total_views})



login_required
def image_ranking(request):
    # Pobranie słownika rankingu obrazów.
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # Pobranie najczęściej wyświetlanych obrazów.
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request, 'images/image/ranking.html',
                  {'section': 'images',
                   'most_viewed': most_viewed})



@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'Liked', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ok'})

@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 18)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:

        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():

            return HttpResponse('')

        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'images',
                       'images': images})
    return render(request,
                  'images/image/list.html',
                   {'section': 'images',
                    'images': images})

imagePortal/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %} Dodaj obraz {% endblock %}

{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

imagePortal/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}
  {% thumbnail image.image "500x500"  as im %}
    <a href="{{ image.image.url }}">
      <img src="{{ im.url }}" class="image-detail">
    </a>
  {% endthumbnail %}
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">

      <div >
        <span class="count">
          <span class="total">{{ total_likes }}</span> polubień
        </span>
          <span class="count">
          <span class="total">{{ total_views }}</span> Wyświetleń
        </span>

        <a href="#" data-id="{{ image.id }}" onClick="window.location.reload()" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Lubię
          {% else %}
            Nie lubię
          {% endif %}
        </a>

      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in image.users_like.all %}

      {% empty %}
        Jeszcze nikt nie polubił obrazu.
        {% endfor %}
    </div>
  {% endwith %}
{% endblock %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // Zmiana wartości atrybutu data-action.
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          // Zmiana tekstu wyświetlanego przez łącze.
          $('a.like').text(previous_action == 'lubię' ? 'Nie lubię' : 'Lubię');
        // Uaktualnienie całkowitej liczby polubienia danego obrazu.
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

imagePortal/images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Dodane obrazy{% endblock %}

{% block content %}
  <h1>Dodane obrazy</h1>
  <div id="image-list">
    {% include "images/image/list_ajax.html" %}
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}

imagePortal/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
  <div class="image">
    <a href="{{ image.get_absolute_url }}">
      {% thumbnail image.image "400x400" crop="100%" as im %}
        <a href="{{ image.get_absolute_url }}">
          <img src="{{ im.url }}">
        </a>
      {% endthumbnail %}
    </a>
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">
      </a>
    </div>
  </div>
{% endfor %}

imagePortal/images/templates/images/image/ranking.html
{% extends "base.html" %}++

{% block title %} Ranking images {% endblock %}
{% block content %}
<h1>Ranking top 10</h1>
<ol>
  {%for image in most_viewed %}
    <li>
      <a href="{{ image.get_absolute_url }}">
        {{ image.title }}
      </a>
    </li>
  {% endfor %}
</ol>
{% endblock %}

imagePortal/images/templates/images/image/upload_image.html
{% extends "base.html" %}
{% block title %} Dodaj obraz {% endblock %}

{% block content %}
    <h1>upload img</h1>
    <form action="." method="post" enctype="multipart/form-data">
        {{ upload_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Upload!!">
    </form>
{% endblock %}